spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgres://zfacuchnuspcgl:c67a80869cb0d0a3af6c6eeb6d8a40151fa5d535afcbb084bcf0298d2ae8dff9@ec2-54-75-224-100.eu-west-1.compute.amazonaws.com:5432/d6pptcuu55002e
    driver-class-name: org.postgresql.Driver
    username: zfacuchnuspcgl
    password: c67a80869cb0d0a3af6c6eeb6d8a40151fa5d535afcbb084bcf0298d2ae8dff9
    hikari:
      maximum-pool-size: 5
  thymeleaf:
    cache: false
    check-template: false
    mode: LEGACYHTML5
server:
  port: 80



